name: Neues Feature vorschlagen
description: Eine neue Funktion für die Software vorschlagen
labels: ["feature", "triage"]
assignees:
  - cloudmaker97
body:
  - type: markdown
    attributes:
      value: |
        Vielen Dank für das Einreichen dieses Features. Damit wird das Projekt enorm unterstützt!
  - type: textarea
    id: description
    attributes:
      label: Feature beschreiben
      description: Eine ausführliche Beschreibung, damit das Feature künftig eingebaut werden kann
      placeholder: Ich würde gerne folgendes Funktion haben...
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Bestätigung zum Inhalt
      description: Ein Fremder sollte diesen Vorschlag auf den ersten Blick verstehen können
      options:
        - label: Ich habe das Feature ausführlich beschrieben und einen aussagekräftigen Titel verwendet
          required: true
