name: Vorschlag einreichen
description: Einen Vorschlag oder eine Idee für das Projekt veröffentlichen
labels: ["enhancement", "triage"]
assignees:
  - cloudmaker97
body:
  - type: markdown
    attributes:
      value: |
        Vielen Dank für das Einreichen dieses Vorschlags. Damit wird das Projekt enorm unterstützt!
  - type: textarea
    id: ehnancement
    attributes:
      label: Vorschlag beschreiben
      description: Eine ausführliche Beschreibung, damit der Vorschlag umgesetzt werden kann
      placeholder: Ich würde gerne folgendes sehen...
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Bestätigung zum Inhalt
      description: Ein Fremder sollte diesen Vorschlag auf den ersten Blick verstehen können
      options:
        - label: Ich habe meinen Vorschlag ausführlich beschrieben und einen aussagekräftigen Titel verwendet
          required: true
